import type { NextRequest } from "next/server";
import { getSessionId } from "@/lib/session";
import { buildBrief, boardSnapshot, publicBrief } from "@/lib/service";
import { renderBriefMarkdown } from "@/lib/brief";
import type { HandoverBrief } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Params = { params: Promise<{ boardId: string }> };

/** The takeaway artifact: a real file the next caregiver can print or forward. */
export async function GET(request: NextRequest, { params }: Params) {
  try {
    const { boardId } = await params;
    const url = new URL(request.url);
    const format = url.searchParams.get("format") === "html" ? "html" : "markdown";
    const handoverAt = url.searchParams.get("handoverAt") ?? new Date().toISOString();
    const shareToken = url.searchParams.get("share");

    const brief = shareToken
      ? await publicBrief(shareToken, handoverAt)
      : await ownerBrief(await getSessionId(), boardId, handoverAt);

    const stamp = brief.generatedAt.slice(0, 16).replace(/[:T]/g, "-");
    const filename = `handover-${brief.subjectName.replace(/[^a-z0-9]+/gi, "-").toLowerCase().slice(0, 40)}-${stamp}.${format === "html" ? "html" : "md"}`;

    if (format === "html") {
      return new Response(renderBriefHtml(brief), {
        status: 200,
        headers: {
          "content-type": "text/html; charset=utf-8",
          "content-disposition": `attachment; filename="${filename}"`,
          "cache-control": "no-store",
        },
      });
    }

    return new Response(renderBriefMarkdown(brief), {
      status: 200,
      headers: {
        "content-type": "text/markdown; charset=utf-8",
        "content-disposition": `attachment; filename="${filename}"`,
        "cache-control": "no-store",
      },
    });
  } catch {
    return new Response(JSON.stringify({ ok: false, error: { code: "export_failed", message: "The brief could not be produced." } }), {
      status: 500,
      headers: { "content-type": "application/json" },
    });
  }
}

async function ownerBrief(sessionId: string, boardId: string, handoverAt: string) {
  const snapshot = await boardSnapshot(sessionId, boardId);
  return buildBrief(snapshot, handoverAt);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderBriefHtml(brief: HandoverBrief): string {
  const rows = (entries: HandoverBrief["incoming"]) =>
    entries
      .map(
        (entry) => `<tr><td>${escapeHtml(String(entry.scheduledFor ?? entry.occurredAt ?? "").slice(11, 16))}</td><td>${escapeHtml(entry.title)}</td><td>${escapeHtml(entry.status)}</td><td>${escapeHtml(entry.assignedTo ?? "unassigned")}</td></tr>`,
      )
      .join("");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>Handover brief - ${escapeHtml(brief.subjectName)}</title>
<style>
 body{font:15px/1.55 ui-serif,Georgia,serif;color:#14211f;background:#f4f1e8;margin:0;padding:32px}
 main{max-width:760px;margin:0 auto}
 h1{font-size:26px;margin:0 0 4px} h2{font-size:16px;margin:28px 0 8px;letter-spacing:.08em;text-transform:uppercase;color:#4a5b57}
 .verdict{display:inline-block;padding:4px 10px;border:2px solid #14211f;font-weight:700;letter-spacing:.06em}
 table{border-collapse:collapse;width:100%;font-size:14px}
 td,th{border-bottom:1px solid #c9c4b4;padding:6px 8px;text-align:left}
 .foot{margin-top:28px;font-size:12px;color:#5b6a66}
 code{font-family:ui-monospace,Menlo,monospace;font-size:12px;word-break:break-all}
</style></head>
<body><main>
<h1>${escapeHtml(brief.subjectName)}</h1>
<p>Handover at ${escapeHtml(brief.asOf)} &middot; readiness <strong>${brief.score}/100</strong> <span class="verdict">${brief.verdict.toUpperCase()}</span></p>
<p>${escapeHtml(brief.decision)}</p>
${brief.blockingIssues.length > 0 ? `<h2>Say out loud before you go</h2><ul>${brief.blockingIssues.map((issue) => `<li>${escapeHtml(issue)}</li>`).join("")}</ul>` : ""}
<h2>Carried by the outgoing person (${brief.outgoing.length})</h2>
<table><tbody>${rows(brief.outgoing)}</tbody></table>
<h2>Inherited by the next person (${brief.incoming.length})</h2>
<table><tbody>${rows(brief.incoming)}</tbody></table>
<h2>Seal</h2><p><code>${escapeHtml(brief.seal ?? "no events yet")}</code></p>
<p class="foot">Generated by Handover at ${escapeHtml(brief.generatedAt)}. ${escapeHtml(brief.disclaimer)}</p>
${brief.sources.length > 0 ? `<p class="foot">Sources: ${brief.sources.map((source) => `${escapeHtml(source.name)} (${escapeHtml(source.status)}, fetched ${escapeHtml(source.fetchedAt)})`).join("; ")}</p>` : ""}
</main></body></html>`;
}